# Generated by Django 4.1.3 on 2022-12-04 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Firstname',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Lastname',
            new_name='lastname',
        ),
        migrations.AddField(
            model_name='profile',
            name='diachi',
            field=models.CharField(default='diachi', max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='huyen',
            field=models.CharField(default='Huyen', max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='idcard',
            field=models.IntegerField(default='00000000000000000'),
        ),
        migrations.AddField(
            model_name='profile',
            name='tinh',
            field=models.CharField(default='Tinh', max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='xa',
            field=models.CharField(default='xa', max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dateofbirth',
            field=models.DateField(default='2000-10-10'),
        ),
    ]
