# Generated by Django 4.1.3 on 2022-12-04 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_goods_namem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='name',
            field=models.CharField(default='Tên tài sản', max_length=100),
        ),
    ]
