# Generated by Django 4.1.3 on 2022-12-05 01:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_goods_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods', models.CharField(default='', max_length=100)),
                ('user', models.CharField(default='', max_length=100)),
                ('price', models.IntegerField(default='20000000')),
                ('datetime', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.AlterField(
            model_name='goods',
            name='user',
            field=models.CharField(default='admin', max_length=100),
        ),
    ]
