# Generated by Django 4.1.3 on 2022-12-05 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_cost_goods_price_alter_history_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='image',
            field=models.ImageField(default='bua4.jpg', upload_to='Goods_images'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='name',
            field=models.CharField(default='Tên tài sản', max_length=300),
        ),
    ]
