# Generated by Django 4.1.3 on 2022-12-05 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_goods_image_alter_goods_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='owner',
            field=models.CharField(default='Nguyễn Văn A', max_length=100),
        ),
        migrations.AddField(
            model_name='goods',
            name='price_now',
            field=models.IntegerField(default='20000000'),
        ),
    ]
