# Generated by Django 4.1.3 on 2022-12-07 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_profile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='price_now',
            field=models.IntegerField(default='20000000'),
        ),
    ]
