# Generated by Django 4.1.3 on 2022-12-10 08:21

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0014_alter_goods_price_now'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='price_now',
            field=models.IntegerField(default='20000000'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default='200000')),
                ('goods', models.CharField(default='1', max_length=200)),
                ('time', models.DateTimeField(default=datetime.datetime(2022, 12, 10, 15, 21, 0, 455389))),
                ('type', models.CharField(choices=[('1', 'Đấu giá thành công'), ('2', 'Đăng bán thành công'), ('3', 'Bán thành công'), ('4', 'Đấu giá không thành công')], default=1, max_length=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
