# Generated by Django 4.1.3 on 2022-12-28 05:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_goods_status_alter_notification_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='status',
        ),
        migrations.AlterField(
            model_name='goods',
            name='type',
            field=models.CharField(choices=[('Đang giao dịch', 'Đang giao dịch'), ('Đã bán', 'Đã bán')], default='Đang giao dịch', max_length=100),
        ),
        migrations.AlterField(
            model_name='notification',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 28, 12, 47, 31, 973663)),
        ),
    ]
