# Generated by Django 4.1.3 on 2022-12-28 05:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_goods_status_alter_goods_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 28, 12, 48, 2, 304288)),
        ),
    ]
