# Generated by Django 4.1.3 on 2022-12-28 08:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_goods_status_alter_notification_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 28, 15, 34, 42, 459997)),
        ),
    ]
