# Generated by Django 4.1.3 on 2022-12-03 08:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import datetime
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.IntegerField(default='1')),
                ('bio', models.TextField(blank=True)),
                ('Firstname', models.CharField(blank=True, max_length=100)),
                ('Lastname', models.CharField(blank=True, max_length=100)),
                ('imagefront', models.ImageField(
                    default='user1.png', upload_to='profile_images')),
                ('imageback', models.ImageField(
                    default='user1.png', upload_to='profile_images')),
                ('phonenumber', models.CharField(blank=True, max_length=100)),
                ('dateofbirth', models.DateField(blank=True, default='0000-00-00')),
                ('gender', models.CharField(blank=True, max_length=10)),
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4,
                 primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=100)),
                ('bio', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='Goods_images')),
                ('startingdate', models.DateTimeField(
                    default=datetime.datetime.now)),
                ('endingdate', models.DateField(default=datetime.datetime.now)),
                ('type', models.CharField(default='Khác', max_length=100)),
                ('cost', models.IntegerField(default='20000000')),
                ('diachi', models.CharField(
                    default='Địa chỉ xem tài sản', max_length=1000)),
                ('time', models.CharField(
                    default='Thời gian xem tài sản', max_length=1000)),
                ('name', models.CharField(default='Tên tài sản', max_length=50)),
            ],
        ),
    ]
