# Generated by Django 4.1.3 on 2022-12-04 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_goods_namem_alter_goods_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='namem',
        ),
    ]
