# Generated by Django 4.1.3 on 2022-12-05 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_goods_endingdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods',
            old_name='cost',
            new_name='price',
        ),
        migrations.AlterField(
            model_name='history',
            name='price',
            field=models.IntegerField(default='20000'),
        ),
    ]
