# Generated by Django 4.1.3 on 2022-12-19 11:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_history_goods_alter_history_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 19, 18, 15, 31, 815092)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.CharField(default='1', max_length=100),
        ),
    ]
